name: SuperHarvest
main: rd.dru.SuperHarvest
version: 1.4
description: "break ores, trees, farms break fast and instanly!"
author: Dru_TNT
api-version: 1.13
commands:
  superharvest:
    description: "superharvest management command"
    aliases: [sh]
permissions:
  superharvest.use:
     description: Allows you to apply super harvest
     default: true
  superharvest.block.*:
     description: Allows you to apply super harvest on specified blocks
     default: true
  superharvest.tool.*:
     description: Allows you to apply super harvest with specified tools
     default: true
  superharvest.mining:
     description: Allows you to apply fast mining
     default: true
  superharvest.farming:
     description: Allows you to apply fast farming
     default: true
  superharvest.logging:
     description: Allows you to apply fast logging
     default: true
  superharvest.admin:
     description: Allows you to use admin cmd
     default: op